version: '3'

services:
  jenkins0:
    image: jenkins:2.60.2
    ports:
      - 8080:8080
      - 9010:9010
    links:
      - socatdockersock
    privileged: true
    volumes:
      - ./.jenkins0:/var/jenkins_home
      - ./.jenkins-backup:/var/jenkins_backup
      - ./.jenkins-workspace:/home/jenkins
      - ./.jenkins-workspace/.jenkins:/home/jenkins/.jenkins

  socatdockersock:
    image: bobrik/socat:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-pro:5.4.5
    container_name: artifactory
    ports:
     - 8081:8081
    volumes:
     - ./.artifactory:/var/opt/jfrog/artifactory
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

  nginx:
    image: docker.bintray.io/jfrog/nginx-artifactory-pro:5.4.5
    container_name: nginx
    ports:
     - 8000:8000
    depends_on:
     - artifactory
    links:
     - artifactory
    volumes:
     - ./.nginx:/var/opt/jfrog/nginx
    environment:
     - ART_BASE_URL=http://artifactory:8081/artifactory
     - SSL=true
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

  sonar:
    image: sonarqube:6.4-alpine
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - ./.sonarqube_new/conf:/opt/sonarqube/conf
      - ./.sonarqube_new/data:/opt/sonarqube/data
      - ./.sonarqube_new/extensions:/opt/sonarqube/extensions
      - ./.sonarqube_new/plugins:/opt/sonarqube/lib/bundled-plugins
